#! /bin/sh

# autostart
pgrep -x sxhkd > /dev/null || sxhkd &
nitrogen --restore &
$HOME/.config/polybar/launch.sh

# workspaces
bspc monitor -d 1 2 3 4 5

# window border configs
bspc config border_width         2
bspc config window_gap          20
bspc config focused_border_color "#8ec07c"
bspc config normal_border_color "#076678"

# split ratio & monocles
bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
